version: '3.8'
services:
  todotests:
    build: ./todo-app/tests/
    environment:
      - FRONT_HOST=frontend
    depends_on:
      - frontend
      - backend
  todofrontend:
    build: ./todo-app/front-end
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=backend
    depends_on:
      - backend
  todobackend:
    build: ./todo-app/back-end
    ports:
      - 3001:3001
